### ISSUE TITLE
Fountain 4 Vim

### ISSUE THREAD

**Issue by stevenjaycohen** [phantomdiorama/writingvim#1]
[Fountain 4 Vim](https://github.com/stevenjaycohen/fountain4vim)

Two wonderful Fountain Plugins for Vim have been unmaintained for a while now:

- [Fountain](https://github.com/vim-scripts/fountain.vim) (A Syntax Highlighter for Fountain Files)
- [Fountain Flow](https://github.com/vim-scripts/fountainflow.vim) (A Fountain Exporter written in VimScript)

This project seeks to combine their functionality and extend where possible.

**Comment by phantomdiorama** [comment]
I have now added this. Thanks a lot!
